# mkdir data
python3 main.py --face-to-edge 0 --meshes-to-points 1 --model pointnet --set-x 0 --lr 0.005 --num-instances 10 --num-sample-points 128 --in-memory-dataset --batch-size 8 --nhid 256 --load-latest --mode submit2
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.005 --num-instances 10 --num-sample-points 1024 --in-memory-dataset --batch-size 8 --nhid 256 --use-txt
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.005 --num-instances 10 --num-sample-points 512 --in-memory-dataset --batch-size 8 --nhid 256 --load-latest --use-txt --mode submit
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.005 --num-instances 10 --num-sample-points 512 --in-memory-dataset --batch-size 8 --nhid 256 --load-latest --use-txt --mode submit
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.005 --num-instances 10 --num-sample-points 512 --in-memory-dataset --batch-size 8 --nhid 256 --load-latest
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.0005 --num-instances 10 --num-sample-points 512 --use-txt --batch-size 8 --save-path /content/drive/MyDrive/ --in-memory-dataset --load-latest
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model simple_edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.0005 --num-instances 10 --num-sample-points 512 --use-txt --batch-size 1 --in-memory-dataset
# python3 main.py --face-to-edge 0 --meshes-to-points 1 --model edge_conv --layer dynamic_edge_conv --set-x 0 --lr 0.0005 --num-instances 5 --num-sample-points 32 --in-memory-dataset
